### ISSUE TITLE
Cant find tab

### ISSUE THREAD

**Issue by mitra42** [abhidas17695/dweb-ext#13]
I sometimes (but not always) get the following error when testing.
```
_generated_background_page.html:1 Error in response to tabs.query: TypeError: Cannot read property 'id' of undefined
    at Object.callback (chrome-extension://bpegplgnpnglnnhlepfjiahmfnbmcegp/scripts/objects-bundle.js:23276:62)
    at Leaf.p_boot (chrome-extension://bpegplgnpnglnnhlepfjiahmfnbmcegp/scripts/objects-bundle.js:23274:37)
    at Function.p_resolveAndBoot (chrome-extension://bpegplgnpnglnnhlepfjiahmfnbmcegp/scripts/objects-bundle.js:23640:34)
```

**Comment by abhidas17695** [comment]
I think this error comes when you try to open the background console while the web page is being reloaded. This problem should not be there any longer since I am not injecting redirect.js in the latest version

**Comment by mitra42** [comment]
OK - will close . Can reopen if/when we see it again
